---
- hosts: all
  vars: 
    dir: '/root/resumeslackbot'

  tasks:
   - name: setup latest nodejs package repo step 1
     shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"
   
   - name: Install nodejs
     shell: 'sudo apt install -y nodejs git'
  

   - name: Install forever
     npm: 
       name: forever
       global: yes
     become: yes
  
   - name: clone git repo
     git:
       repo: 'https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.ncsu.edu/csc510-fall2019/CSC510-20.git'
       dest: '{{dir}}'
   
   - name: Install nodejs
     shell: 'git checkout experimental'
     args:
       chdir: "{{dir}}"
     
   - name: npm install
     command: 'npm install --save'
     args:
       chdir: '{{dir}}'
       
   - name: 'copy .env'
     copy:
       src: '/home/rr/Workspace/csc510-20/.env'
       dest : '{{dir}}'
       
   - name: 'copy cookies'
     copy:
       src: '/home/rr/Workspace/csc510-20/resources/cookies'
       dest : '{{dir}}/resources/'
   
   - name: run the app
     command: 'forever start -o out.log -e err.log index.js'
     args:
       chdir: '{{dir}}'

# ansible-playbook -i inventory task.yml -e "githubuser=***" -e "githubpassword=***"
